name: Deployment - Reusable Workflow

on:
 workflow_call:

jobs:
    unit-test:
        name: Unit Testing
        runs-on: ubuntu-latest
        # container Service , sidecar container that work with the same network
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017 #Port Mapping
        env:
          MONGO_URI: "mongodb://localhost:27017/superData"
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
    
    deploy:
      runs-on: ubuntu-latest
      
      environment:
        # Name of The environment in Github
        name: development
        url: https://${{ steps.Set-ingress-host-address.outputs.APP_INGRESS_HOST}}

      outputs:
        APP_INGRESS_URL: ${{ steps.Set-ingress-host-address.outputs.APP_INGRESS_HOST}}

      steps:
        - name: Checkout The Repository
          uses: actions/checkout@v5
          # Install k8s on the VM 
        - name: Install Kubectl
          uses: azure/setup-kubectl@v4

          # Set The Kubeconfig file To operate on the K8s Clusters
        - uses: azure/k8s-set-context@v5
          with:
           method: kubeconfig
          # I put it in The Development Environment Secrets
           kubeconfig:  ${{ secrets.KUBECONFIG }}

        - name: Testing Operation of The K8s Cluster
          run: kubectl get nodes

        - name: Get Nginx Ingress Controller ip
          run: |
           echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
      
        - name: Replace Tokens
          uses: cschleiden/replace-tokens@v1
          with:
           tokenPrefix: '_{_'
           tokenSuffix: '_}_'
           files: '["kubernetes/development/*.yaml"]'
          #  Get All these Env From Environment Variables
          env:
           NAMESPACE: ${{vars.NAMESPACE}}
           REPLICAS: ${{vars.REPLICAS}}
           IMAGE: ${{vars.DOCKER_USERNAME}}/solarsystem:${{github.sha}}
          #  Get it from $GITHUB_ENV => env.
           INGRESS_IP: ${{env.INGRESS_IP}}

        # Create of The Securet Refrence in K8s 
        - name: Create The Secret Ref
          run: | 
           kubectl -n ${{vars.NAMESPACE}} create secret generic mongo-db-creds \
           --from-literal=MONGO_URI=${{env.MONGO_URI}} \
           --from-literal=MONGO_USERNAME=${{env.MONGO_USERNAME}} \ 
           --from-literal=MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}} \
           --save-config \
           --dry-run=client \
           -o yaml | kubectl apply -f -

        
        - name: Deploy to Dev Env
          run: |
            kubectl apply -f kubernetes/development
            sleep 20

        - name: Set Application Host URL
          id: Set-ingress-host-address
          run: |
            echo "APP_INGRESS_HOST=$(kubectl -n development get ingress -o jsonpath="{.items[0].spec.tls[0].hosts[0]}")" 